#:schema node_modules/wrangler/config-schema.json
name = "example-cf-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "example_kv"
id = "d76a2c9d9c954fe4bf5c97779fded66c"
preview_id = "1006fc8b47da43f79f069c460c995b0a"